### ISSUE TITLE
ProcessMethod::numberInLocation работает не так как ожидается

### ISSUE THREAD

**Issue by nsr888** [nsr888/webserver#16]
`if (_config->getLocationPath(i) == path)`
Считаю, что это сравнение не корректно, так как реальный путь запроса может быть длиннее чем путь из локейшна.

Например, приходит запрос: `/put_tests/somefile.gif`
В локейшне для  `/put_tests`, указан root: `/Users/.../webserver/files/put_tests/`
Реальный путь сформируется такой: `/Users/.../webserver/files/put_tests/somefile.gif`

**/Users/.../webserver/files/put_tests/somefile.gif != /Users/.../webserver/files/put_tests/**

**Comment by Litvinovis** [comment]
Работаю над этим в check_path

**Comment by Litvinovis** [comment]
Done
