### ISSUE TITLE
Добавить в конфиг параметр debug_level

### ISSUE THREAD

**Issue by nsr888** [nsr888/webserver#18]
Предлагаю добавить параметр, который бы отвечал за вывод отладочных сообщений в консоль.
Можно, например, обозначать цифрами:
- debug_level = 0
не выводить отладочные сообщения
- debug_level = 1
выводить отладочные сообщения по минимуму, например только код запроса и ответа
- debug_level = 2
выводить все отладочные сообщения

**Comment by Litvinovis** [comment]
Done

**Comment by Litvinovis** [comment]
How to use:

   if (config[0].getDebugLevel()) {
        std::cout << 	                 
    }
