### ISSUE TITLE
Config: Can't setup error pages for all possible types of errors

### ISSUE THREAD

**Issue by nsr888** [nsr888/webserver#25]
**Is your feature request related to a problem? Please describe.**
Can't setup error pages for all possible types of errors in config. 
For now, only one error_page is accessible for setup.

**Describe the solution you'd like**
I expected, that this will work like In nginx config.
For example, I can write this in nginx config:
```
server {
    ...
    error_page 404 /404.html;
    error_page 405 /405.html;
    error_page 406 /common_error.html;
    error_page 407 /common_error.html;
    ...
}
```

**Describe alternatives you've considered**
If we rename current config parameter `error_page` to `error_404_page`.
That will be clearly. And maybe it will be ok for project validation.

**Additional context**
INTRA check list has this check:
- setup default error page (try to change the error 404)

**Comment by Litvinovis** [comment]
Added second 404 error page for switch
