### ISSUE TITLE
Test GET Expected 404 on http://localhost:8080/directory/oulalala

### ISSUE THREAD

**Issue by nsr888** [nsr888/webserver#26]
**Describe the bug**
Tester stop at this point: `Test GET Expected 404 on http://localhost:8080/directory/oulalala`
But webserv send response: `HTTP/1.1 200 OK`

**To Reproduce**
1. Run ./webserv
2. Run ./tests/tester http://localhost:8080

**Expected behavior**
Expected 404 error: `HTTP/1.1 404 Not Found
`

**Comment by Litvinovis** [comment]
Fixed
