### ISSUE TITLE
Имплементировать все заголовки согласно чеклисту

### ISSUE THREAD

**Issue by nsr888** [nsr888/webserver#27]
**Is your feature request related to a problem? Please describe.**
Согласно чеклисту у нас должны быть импелементированы, следующие заголовки.
Отметил какие уже сделаны:
- [x] Accept-Charsets
- [x] Accept-Language
- [x] Allow
- [x] Authorization
- [x] Content-Language
- [x] Content-Length
- [x] Content-Location
- [x] Content-Type
- [x] Date
- [x] Host (почему то при  POST запросе не верно выставляется server_name)
- [x] Last-Modified
- [x] Location
- [ ] Referer
- [ ] Retry-After
- [x] Server
- [x] Transfer-Encoding
- [ ] User-Agent
- [x] WWW-Authenticate

**Describe the solution you'd like**
Приходящие в запросе заголовки из списка выше должны обрабатываться корректно.
Все допустимые исходящие заголовки из списка выше должны присутствовать в ответе.

**Comment by kozarezov** [comment]
Accept-Charsets
Accept-Language
Allow

Добавлены
