### ISSUE TITLE
In the config we can't setup same port multiple times

### ISSUE THREAD

**Issue by nsr888** [nsr888/webserver#28]
**Describe the bug**
According to INTRA check list we cant setup same port multiple times. Cite from check list:
> - In the configuration try to setup the same port multiple times. It should not work.

**To Reproduce**
1. Go to 'default.conf'
2. Set port multiple times: 
```
server: {
...
port: 8080
port: 8080
...
}
```
4. Launch webserv
5. The webserv launch without problem

**Expected behavior**
Error message: config is incorrect. 

**Additional context**
nginx show this error:
`nginx: [emerg] a duplicate listen 0.0.0.0:9090 in /usr/local/etc/nginx/nginx.conf:18`
when listen port setted multiple times in config:
```
server {
...
          listen       9090;
          listen       9090;
...
}
```

**Comment by Litvinovis** [comment]
Два сервера с одинаковыми портами не запускаются, проверка на это уже давно добавлена

**Comment by Litvinovis** [comment]
Если прописать два раза подряд в настройках одного сервера то используется последняя инструкция, первая игнорируется
