### ISSUE TITLE
При запросе PUT формируется не правильный путь

### ISSUE THREAD

**Issue by nsr888** [nsr888/webserver#29]
**Describe the bug**
При запросе PUT формируется не правильный путь

**To Reproduce**
1. Запустить вебсервер
2. Запустить телнет: `telnet localhost 8080`
3. Вставить следующий запрос в телнет:
```
PUT /put_test/test.txt HTTP/1.1
Host: localhost
Content-Type: text/plain
Content-Length: 27
Accept: text/plain

key1=VALUE1&key2=value22255
```
4. Сервер вернет: `Response.cpp: setPath is /Users/anasyrov/Documents/21/webserver/_webserver/files//index.html` и как результат `HTTP/1.1 405 Method Not Allowed
`
**Expected behavior**
Реальный путь должен быть выставлен так: /Users/anasyrov/Documents/21/webserver/_webserver/files/put_test/test.txt

**Comment by Litvinovis** [comment]
Fixed
