### ISSUE TITLE
Seg fault на заведомо некорректном POST запросе, при компиляции через g++10

### ISSUE THREAD

**Issue by nsr888** [nsr888/webserver#31]
**Describe the bug**
Программа сегается на POST запросе, если скомпилировать сервер через g++10.
Ошибка вроде бы в функции `utils::ft_strtrim`, на строке 112:
`while (s1[index] && utils::ft_strchr(set, s1[index]) != -1)`
Если скомпилировать clang++, то все ок.

**To Reproduce**
1. В Makefile указать в качестве компилятора g++10
2. Скомпилировать.
3. Запустить сервер.
4. Запустить телнет: `telnet localhost 8080`
5. Вставить запрос:
```
POST /onhuneothunheo HTTP/1.1
Accept: text/plain
Accept-Encoding: identity
Content-Length: 17
Content-type: application/x-www-form-urlencoded
Host: localhost:8080

key1=val&key2=va2
```
6. Появится сега

**Expected behavior**
Возможно не должно быть сеги ))

**Screenshots**
[Screenshot 1](https://ibb.co/v4NdHkt)
[Screenshot 2](https://ibb.co/rHjQzwv)

**Comment by Litvinovis** [comment]
невозможно воспроизвести ошибку, потому что раньше выходит ошибка:

g++-10 -Wall -Wextra -Werror -g -O2 -std=c++98 -pedantic -MMD -MP -Ilibft -Ignl -c ProcessMethod.cpp -o ProcessMethod.o
ProcessMethod.cpp: In member function ‘void ProcessMethod::_execCGI(const string&)’:
ProcessMethod.cpp:256:12: error: ignoring return value of ‘int mkstemp(char*)’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
  256 |     mkstemp(request_body);
      |     ~~~~~~~^~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

**Comment by nsr888** [comment]
Убрал mkstemp, просьба проверить.

**Comment by Litvinovis** [comment]
------ Response Start (first 400 symbols) -------
HTTP/1.1 404 Not Found
Content-Language: en-US, ru-RU
Content-Length: 369
Content-Location: /onhuneothunheo
Content-Type: text/html;charset=utf-8
Date: Wed,  25 May 2021 13:37:15 GTM
Server: localhost

<html>
    <head>
        <meta charset="UTF-8">
    </head>
    <body>
        <h1 style="text-align: center;"><kbd><font size="6"><font face="Arial, Helvetica, sans-serif">ОШИБКА 404
------ Response End (first 400 symbols) -------

**Comment by Litvinovis** [comment]
Сега не выходит, предлагаю не использовать g++10 ¯\_(ツ)_/¯
