### ISSUE TITLE
Test GET http://localhost:8080/directory/nop FATAL ERROR ON LAST TEST: bad status code

### ISSUE THREAD

**Issue by nsr888** [nsr888/webserver#32]
**Describe the bug**
В тестере стоим на этом пункте:
```
Test GET http://localhost:8080/directory/nop
FATAL ERROR ON LAST TEST: bad status code
```
сервер возвращает HTTP/1.1 404 Not Found
и real_path выставляется не правильно: 
/Users/anasyrov/Documents/21/webserver/_webserver/files/YoupiBanane/nop

**To Reproduce**
Запустить сервер и тестер с интры.

**Expected behavior**
Должен выставляться такой путь:
/Users/anasyrov/Documents/21/webserver/_webserver/files/YoupiBanane/nop/youpi.bad_extension

**Comment by nsr888** [comment]
И из за этого тест с аутентификацие валится, так как там 
real_path выставляется /Users/anasyrov/Documents/21/webserver/_webserver/files/auth/
а должен: /Users/anasyrov/Documents/21/webserver/_webserver/files/auth/index.html

**Comment by Litvinovis** [comment]
Done
