### ISSUE TITLE
Пустая страница по запросу http://localhost:8080/oeuneohu вместо 404 ошибки

### ISSUE THREAD

**Issue by nsr888** [nsr888/webserver#33]
**Describe the bug**
Пустая страница по запросу http://localhost:8080/oeuneohu вместо 404 ошибки.
Выставляется такой путь:
`setPath is /Users/anasyrov/Documents/21/webserver/_webserver/files/oeunheou`
Статус возвращается правильный: `HTTP/1.1 404 Not Found`.
Но в браузере открывается белая страница, из за того что передается Content-Length: 0 и пустое body.

**To Reproduce**
1. Запустить сервер
2. Открыть в браузере http://localhost:8080/oeuneohu
3. Увидеть пустую страницу

**Expected behavior**
Так как файла 404.html не существует, то я ожидал увидеть текст дефолтной 404 ошибки.
Если указать корректную страницу для ошибки, то все работает корректно.
Если убрать вообще строку с указанием страницы ошибки, то также не работает.

**Comment by Litvinovis** [comment]
Путь всегда так выставлялся, потом проверяется на существование и если нет, возвращается 404, наверное нужно в части Дениса поправить длину тела, сначала

**Comment by Litvinovis** [comment]
Денис вроде починил

**Comment by nsr888** [comment]
Убрал указание файла ошибки в конфиге для рута и проблема повторилась

**Comment by Litvinovis** [comment]
Денис вроде починил (х2)
