### ISSUE TITLE
http://localhost:8080/auth/ выдает 405 ошибку

### ISSUE THREAD

**Issue by nsr888** [nsr888/webserver#34]
**Describe the bug**
http://localhost:8080/auth/ выдает 405 ошибку

**To Reproduce**
1. Открыть http://localhost:8080/auth/
2. Ввести логин Admin, пароль 123456
3. Увидеть 405 ошибку

**Expected behavior**
Должен быть 200 ответ и выводится страница:
.../files/auth/index.html

**Comment by Litvinovis** [comment]
fixed by denis
