### ISSUE TITLE
Дата выводится не правильно

### ISSUE THREAD

**Issue by nsr888** [nsr888/webserver#35]
**Describe the bug**
Выводится сегодня такая дата:
Date: Sun,  -1 Jun 2021 12:49:27 GTM
Не правильное число, не правильное смещение времени и вместо GTM, должно быть GMT

**To Reproduce**
1.  Открыть http://localhost:8080/
2. В логах увидеть неверную дату

**Expected behavior**
Ожидал увидеть такую дату:
Date: Sun,  30 May 2021 09:49:27 GMT

**Comment by Litvinovis** [comment]
fixed by denis
