### ISSUE TITLE
Не верный Content-Type  при открытии директории с автоиндексом

### ISSUE THREAD

**Issue by nsr888** [nsr888/webserver#36]
**Describe the bug**
Выставляется не верный Content-Type: application/octet-stream при открытии директории с включенным автоиндексом.

**To Reproduce**
1. Открыть в браузере страницу: localhost:8080/get_test/
2. Вместо страницы передается файл на скачивание.

**Expected behavior**
Ожидал увидеть страницу с листингом директорий.

**Comment by Litvinovis** [comment]
fixed by denis
